language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

notifications:
  slack:
    - secure: "d+XOjAqK7K4FMUrDKOgrAJCZizkck9cicmniJCwo1CB2izuhs5sM1KUxeOwoKKoKvIVvWQ3NMYYuOWvUtgn/8KA8C/boIvxI+10galOy2QGIYxgL3wzpTUAiABDUoMOwW+wG1YT4nDzVMptfcKKiq2TnfjX4MFW/7ayEdS1ihMs4FhhePEV/KQwjipVVADCehgiOMOImQD4gVuaVsUdlsxUNy+ekvYpVcBBaNi2XiuIM0jR+HbgNedZNo8eWEOi/UQibmKRMBxaCmG+7Fm0swvZk17FIT54h5Fv4AEjgptzaPKxLAvkRUUt3q8XH2dp8x5BG/l13EEJrOqjxLcnfIbnDAxoQB7k6H6VCfIj28qYcBPTTcR+6vrxTsWl80VPbDSLFc9KDqEpDWcm4+uTZ0sOYLSW48UZwjjmGZJ1hWFAnWnv/Z1XXJoCVgQIFdyzv+K0ohJOwOc9JpjoJuB0YYOYAe7wj/JRYuUJJA5EhWQOKmNIcUPmodrhoKo7kUMeGctuL9UrKS1u+Jb82drDif8beHROyDxr22UeewhUTB2EU2dO0742PIwvaGWgzsDnRo4pzQohrE18fOHPsLhqZ5/yMsbC58d1W8uRqDWO618tmKJFYcpKd0UY2/kAREX2oDfN/AOX5jqFDo2Lb3Xv+3fMZuINheygFqtFwRoZx8XY="
